// src/components/Typed.tsx
import { useEffect, useRef, type FC } from "react";
import type { TypedOptions } from "typed.js";
import TypedJs from "typed.js";

type Props = {
  strings: string[];
  options?: TypedOptions;
};

export const Typed: FC<Props> = ({ strings, options }) => {
  const el = useRef(null);

  const defaultOptions = {
    strings,
    typeSpeed: 5,
    loop: true,
    startDelay: 800,
    backDelay: 3000,
    showCursor: false,
    ...options,
  };

  useEffect(() => {
    const typed = new TypedJs(el.current, { ...defaultOptions });
    return () => {
      typed.destroy();
    };
  }, []);

  return (
    <span
      ref={el}
      className="px-4 flex flex-wrap place-items-center w-full min-h-16 max-w-screen-lg text-2xl text-center"
    />
  );
};

// src/svelte/typed/Typed.svelte
<script lang="ts">
  import type { TypedOptions } from "typed.js";
  import { onMount } from "svelte";
  import { getInit } from './typed.service';

  export let strings: string[] | null;
  export let options: TypedOptions;

  onMount(getInit(strings, options));
</script>

<span id='typed' class="typed" />

<style lang="scss">
  .typed {
  @apply px-4 flex flex-wrap place-items-center
  w-full min-h-16 max-w-screen-lg text-2xl text-center;
}
</style>
